services:
  beet:
    build: .
    container_name: beet
    volumes:
      - ./config.yaml:/config/config.yaml
      - ./library:/library
      - '/mnt/storage/Music - Import/:/import'
      - /mnt/storage/Music2:/music
    entrypoint: /app/.venv/bin/beet
    environment:
      EDITOR: vim
      TZ: Asia/Singapore
      BEETSDIR: /config
