services:
  beet:
    build: .
    volumes:
      - '/mnt/storage/Music - Import/:/import'
      - /mnt/storage/Music:/music
      - ./data:/data
      - ./data/checksum:/usr/bin/checksum
      - ./config.yaml:/root/.config/beets/config.yaml
    entrypoint: beet
    environment:
      EDITOR: vim
      TZ: Asia/Singapore
