services:
  beet:
    build: .
    volumes:
      - .:/app
      - '/mnt/storage/Music - Import/:/import'
      - /mnt/storage/Music:/music
    entrypoint: /home/vscode/.local/bin/pdm run beet
    environment:
      EDITOR: vim
      TZ: Asia/Singapore
      BEETSDIR: /app
